packages:
  - 'packages/*'
  - 'tools/*'
  - 'apps/*'
allowBuilds:
  '@parcel/watcher': set this to true or false
  '@swc/core': true
  less: set this to true or false
  msw: true
  nx: true
  sharp: set this to true or false
  unrs-resolver: true
