FROM mcr.microsoft.com/devcontainers/base:bookworm

# Install additional OS packages
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-packages-here> \
#     && apt-get clean && rm -rf /var/lib/apt/lists/*
